name: Lint

on: [push, pull_request]

jobs:
  flake8_lint:
    name: flake8
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install flake8 and flake8-tabs
        run: pip install flake8 flake8-tabs

      - name: Run flake8
        run: flake8 . --config .flake8
