name: Extract strings for translation

on: [push, pull_request]

jobs:
  translations:
    name: flake8
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Extract strings
        run: python3 lifesim-translate.py
